/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_246492: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_13202: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_246494: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_233053: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_4: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_7434: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_7434_6: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_7: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_8: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_7434_9: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_10: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_11: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_12: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_7434_13: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13201_14: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_13200: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_3428: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_4979: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_13203: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
